# Generated by Django 5.2.5 on 2025-11-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('parent_account_id', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_accounts',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_id', models.IntegerField(blank=True, null=True)),
                ('txn_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('txn_type', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=255)),
                ('imported_from', models.JSONField(blank=True, null=True)),
                ('matched_payment_id', models.IntegerField(blank=True, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_bank_transactions',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=32)),
                ('line_items', models.JSONField(default=list)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_bills',
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('claim_date', models.DateField()),
                ('items', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(max_length=32)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_expense_claims',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=32)),
                ('line_items', models.JSONField(default=list)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_invoices',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_journal_entries',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(max_length=50)),
                ('from_account_id', models.IntegerField(blank=True, null=True)),
                ('to_account_id', models.IntegerField(blank=True, null=True)),
                ('related_invoices', models.JSONField(blank=True, null=True)),
                ('related_bills', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='posted', max_length=32)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_txn_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_payments',
            },
        ),
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=32)),
                ('line_items', models.JSONField(default=list)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_supplier_bills',
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_period', models.DateField()),
                ('tax_type', models.CharField(max_length=32)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source', models.JSONField()),
                ('file_meta', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'finance_tax_records',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('party_type', models.CharField(blank=True, max_length=50, null=True)),
                ('party_id', models.IntegerField(blank=True, null=True)),
                ('tax_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'db_table': 'finance_journal_lines',
            },
        ),
    ]
